### PR TITLE
ci: add nodejs 16 to matrix

### PR DESCRIPTION
**Pull request by Fdawgs**
#### Checklist

- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Fdawgs** [comment]
Coveralls seems to be having issues atm, parallel coverage collection stage is failing in this and in my own repos.
Will wait until this evening to rerun action.

**Comment by climba03003** [comment]
@Fdawgs Is it problem with the github token?
The job inside test is using `github-token: ${{ secrets.github_token }}`

**Comment by Fdawgs** [comment]
> 
> 
> Reference: [lemurheavy/coveralls-public#1543](https://github.com/lemurheavy/coveralls-public/issues/1543)

Cheers @climba03003, good to see they are investigating!

**Review by climba03003 — APPROVED** [review]
Coveralls is back. LGTM.

**Pull request merged**
