### PR TITLE
Add decorateReply options

### PR DESCRIPTION
**Pull request by allevo**
`decorateReply` option allow you to decorate the `Reply` class too.

Each method has prepended "request" string like "requestTypes"

### CODE REVIEW

**Comment by mcollina** [comment]
The main question is why this change? Isn't it sufficient to have this on `Request`? If there is a need for `Reply` to have a public access to `Request`, then let's do that in fastify.

**Comment by allevo** [comment]
In some cases the `Request` access is not allowed. For example in `decorateReply`. 

Expose the whole `Request` from `Reply` can be tricky for the circular inclusion.

Here it is sufficient to access to `IncomingMessage`.

**Comment by delvedor** [comment]
I agree with @mcollina, this change seems to be more work than needed.
The decorateReply could accept a req argument and your are done.
```js
fastify.decorateReply('util', function (req) {
  // do something with req
  return this
})

fastify.get('/', (req, reply) => {
  reply.util(req).send(something)
})
```
I'd like to maintain separates the two things.

In any case you can always access the `reply._req` object.

**Comment by allevo** [comment]
I'm thinking to https://github.com/fastify/fastify/issues/146 where the `serializer` function is binded to `Reply` instance and accepts only the object that will be serialized.

**Comment by mcollina** [comment]
@allevo are you thinking of building another plugin on top of this one that supports that feature?

@delvedor I don't see your functionality better off than this one introduces. Multiple plugins that would need a way to expose the same request object would conflict then. Plus, we will still hold the `Request` object forever.

How about:

```js
res.sendType(req.accepts(), { hello: 'world' })
```

for the other plugin? This should keep things separate.

**Comment by allevo** [comment]
@mcollina yes. I'd like to write a plugin that serializes automatically the content passed to `send` `Reply` method according to the accept header.

*And more*:
Ideally we can remove those lines https://github.com/fastify/fastify/blob/master/lib/reply.js#L28-L105 to split them into multiple plugins that handle the output correctly.
Splitting the output logic into different plugin, we can manage the output correctly for "all kind of object" passed to the `send` method (stream, Boom error, Error etc...).

For the time being, I think fastify supports only json output in case of error.

**Comment by mcollina** [comment]
So, I'm -1 in making `send()` more high-level than it is right now. It also includes some fast-paths that are not easily reproducible if split across. In a similar way, I'm not keen in overriding `send` to make it automatically pick the right serialization type: that is a feature that might or might not be wanted so it should live in a plugin (and a separate method). Putting too many functionality on the same method slow things down considerably.

Regarding the errors, it's a known missing feature, and it should be addressed separately from this https://github.com/fastify/fastify/issues/135 (PR welcome as always!)

**Comment by allevo** [comment]
@mcollina My aim is not to inject this plugin into fastify core in order to support different serializer types. This is a plugin, not the core.

I'd like to see a more structured `Serializer` "class". The fastify instance has a ordered list of `Serializer` instance that has those methods:
- isAbleToSerializer(req, body) // match ?
- serialize(body) // return a string
- serializeError(error) (*)
- serializeStream(stream) (*)

The first match wins.
In this way we can support all kind of output without loosing perfs.
Obviously, the default one has the same code of `send` method.

\* is needed?

**Comment by mcollina** [comment]
@allevo I really do not like that approach. It is too complex. Altering the behavior of a hot-path function via polymorphism is the way to slow throughput. I think send is as good as it could be with fastify/fastify#135 fixed. All that functionality can (and probably should) be implemented outside.

**Comment by allevo** [comment]
> Altering the behavior of a hot-path function via polymorphism is the way to slow throughput
@mcollina  I agree to avoid all polymorphism from the `send` method but I don't see any polymorphisms here: a simple "for" loop to find which `Serializer` instance is able to serialize for that reply and a call to the right method.

Anyway, the `send` method can stay as is. It's structured to be performant as fast as possible.

But fastify needs to separate the `serialization` phase from the socket write.

**Comment by allevo** [comment]
@mcollina @delvedor as is

For any other features or improvements, I'll open an issue or pr.

**Pull request merged**
