### PR TITLE
feat: preparation for fastify@5

### PR DESCRIPTION
**Pull request by bilalshareef**
Ref: [fastify/fastify#5116](https://github.com/fastify/fastify/issues/5116)

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by bilalshareef** [comment]
Please create a **next** branch for this pull request.
@simoneb

**Comment by simoneb** [comment]
done

**Review by simoneb — APPROVED** [review]
LGTM

**Comment by nrayburn-tech** [comment]
I think this should be updated as well.
https://github.com/fastify/fastify-accepts/blob/aa4220803b9eccc0d25e541813b0a989eb00afe9/index.js#L58

https://github.com/fastify/any-schema-you-like/issues/56#issuecomment-1792402093

**Comment by bilalshareef** [comment]
> I think this should be updated as well.
> 
> https://github.com/fastify/fastify-accepts/blob/aa4220803b9eccc0d25e541813b0a989eb00afe9/index.js#L58
> 
> [fastify/any-schema-you-like#56 (comment)](https://github.com/fastify/any-schema-you-like/issues/56#issuecomment-1792402093)

@nrayburn-tech, Updating the version here leads to FST_ERR_PLUGIN_VERSION_MISMATCH error. So this change can be made only after Fastify v5 is released and available.

**Review by gurgunday — APPROVED** [review]

**Pull request merged**
