### PR TITLE
Integrate accepts type definitions

### LINKED ISSUE #154: Typescript Build Error on Accepts
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hey there, 

Not sure whether this should be raised as a bug or not but when trying to install this in a TS project as this may be intended but I received the following error:

https://github.com/seek-oss/slowify/actions/runs/5167692569/jobs/9308739911

```
Error: tsc      │ node_modules/@fastify/accepts/types/index.d.ts(1,25): error TS7016: Could not find a declaration file for module 'accepts'. '/home/runner/work/slowify/slowify/node_modules/accepts/index.js' implicitly has an 'any' type.
```

Could `@types/accepts` be made a dependency for this library to avoid consumers needing to install it themselves?

### PR DESCRIPTION
**Pull request by samchungy**
Resolves https://github.com/fastify/fastify-accepts/issues/154

### CODE REVIEW

**Review by Uzlopak — CHANGES_REQUESTED** [review]
We should actually remove the types package, as we supply the types with this package. See types/index.d.ts

**Comment by samchungy** [comment]
> We should actually remove the types package, as we supply the types with this package. See types/index.d.ts

Hmmm but you're importing it though right?

https://github.com/fastify/fastify-accepts/blob/f098ec0541e92546c7689e2c7e2c563d2e588f15/types/index.d.ts#L1

**Comment by Uzlopak** [comment]
I am tending to say that we should integrate accepts with the types into this package.

**Comment by samchungy** [comment]
Screenshot_20230605-093610

Okay @Uzlopak the types package dependency is pretty tiny, would you like a straight copy of the types from index.d.ts? Happy to do it, but there a few different ways we could structure it

**Comment by Uzlopak** [comment]
We should also add https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/accepts/accepts-tests.ts to our tests.

**Comment by samchungy** [comment]
Can we retry that run? Doesn't seem to be related to the PR 👀

**Comment by Eomm** [comment]
We need an empty commit to rerun the updated workflow - then it should be green and good to go

**Review by Uzlopak — APPROVED** [review]
LGTM

**Comment by Uzlopak** [comment]
@samchungy 

Thank you for your work
@eomm
Can you release please?

**Comment by Eomm** [comment]
Done

If you want to try, I run these scripts locally:

```
once after first installation:
releasify config --arg verbose -v debug
releasify config --arg gh-token

to release:
releasify draft -s minor -n
releasify publish -s minor -n --gh-release-body
```

**Comment by Uzlopak** [comment]
@Eomm 
Afaik i am lacking npm permissions

**Comment by Eomm** [comment]
lolz (?)

Do you wish to release them?

I think you may need to request to be added to the plugin team
You are no-where 😅 https://github.com/fastify/fastify#team

Write to the person who brought you onboard

**Pull request merged**
